export const SliderData = [
    [{
        image:
            'https://i.imgur.com/JudUnYl.png'
    },
    {
        image:
            'https://i.imgur.com/2qTP1f4.png'
    },
    {
        image:
            'https://i.imgur.com/aFf39z1.png'
    },
    {
        image:
            'https://i.imgur.com/7GZbxCV.png'
    }
    ],
    [{
        image:
            'https://i.imgur.com/bbJLm00.png'
    },
    {
        image:
            'https://i.imgur.com/7qYt7dU.png'
    }
    ],
    [{
        image:
            'https://i.imgur.com/zwCvWfY.png'
    },
    {
        image:
            'https://i.imgur.com/7qYt7dU.png'
    }
    ],

]